version: '3'
services:
  mongodb:
    image: mongo:7.0.7
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - chatogether_net
    volumes:
      - mongo:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  mongo_express:
    depends_on:
      - mongodb
    image: mongo-express:1.0.2-20
    container_name: mongo_express
    restart: always
    ports:
      - "8081:8081"
    networks:
      - chatogether_net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongodb


  db:
    image: mysql:8.0.36
    volumes:
      - chatogether_db_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - chatogether_net

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_PORT: 3306
      CHATOGETHER_DB_PWD: ${CHATOGETHER_DB_PWD}
    networks:
      - chatogether_net
    volumes:
      - .:/backend

volumes:
  mongo: {}
  chatogether_db_vol:

networks:
  chatogether_net:
    external: true